trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: default
    continueOnError: true
    steps:
    - task: vsts-habitat-install@3
      displayName: 'Install Habitat'
    - task: vsts-habitat-signing-key@3
      displayName: 'Signing Origin Key: install'
      inputs:
        habitatOrigin: 'Habitat Depot'
    - task: vsts-habitat-build@3
      displayName: 'Build Habitat plan'
      inputs:
        habitatOrigin: 'Habitat Depot'
      env:
        HAB_LICENSE: accept-no-persist
    - task: vsts-habitat-expose-habitat-build-vars@3
      displayName: 'Expose Habitat Build Variables'
      inputs:
        habitatSetBuildNumber: true
    - publish: $(System.DefaultWorkingDirectory)/results
      artifact: hart

- stage: DeployToDev
  jobs:
  - deployment: deployment
    pool:
      name: default
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
            displayName: 'Install Habitat'
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: 'Habitat Depot'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                . $(Pipeline.Workspace)/hart/last_build.ps1
                echo "##vso[task.setvariable variable=pkg_artifact]$pkg_artifact"
            displayName: 'Publish Artifact Name'
          - task: vsts-habitat-pkg-upload@3
            displayName: 'Package Upload'
            inputs:
              habitatOrigin: 'Habitat Depot'
              habitatPackagePath: '$(Pipeline.Workspace)/hart/$(pkg_artifact)'
              habitatPackageChannel: dev
            env:
              HAB_LICENSE: accept-no-persist

- stage: DeployToStg
  jobs:
  - deployment: deployment
    pool:
      name: default
    environment: 'stg'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
            displayName: 'Install Habitat'
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: 'Habitat Depot'
          - powershell: |
              . $(Pipeline.Workspace)/hart/last_build.ps1
              C:\ProgramData\habitat\hab.exe pkg promote $pkg_ident stage
            displayName: 'Promote to Stage'
            env:
              HAB_LICENSE: accept-no-persist

- stage: DeployToProd
  jobs:
  - deployment: deployment
    pool:
      name: default
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: vsts-habitat-install@3
            displayName: 'Install Habitat'
          - task: vsts-habitat-signing-key@3
            displayName: 'Signing Origin Key: install'
            inputs:
              habitatOrigin: 'Habitat Depot'
          - script: 'C:\ProgramData\habitat\hab.exe license accept'
            displayName: 'Accept Hab license'
          - powershell: |
              . $(Pipeline.Workspace)/hart/last_build.ps1
              C:\ProgramData\habitat\hab.exe pkg promote $pkg_ident prod
            displayName: 'Promote to Prod'
            env:
              HAB_LICENSE: accept-no-persist